# Generated by Django 4.2.10 on 2024-02-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='calories',
            field=models.TextField(default='100'),
        ),
    ]
